// <auto-generated />
using System;
using BaiTap_23WebC_Nhom10.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTap_23WebC_Nhom10.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023023146_Tag")]
    partial class Tag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiTap_23WebC_Nhom10.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryID")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<DateTime>("createAT")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_AT");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DISCOUNT");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IMAGE");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRODUCT_NAME");

                    b.Property<int?>("quality")
                        .HasColumnType("int")
                        .HasColumnName("QUALITY");

                    b.Property<int>("selled")
                        .HasColumnType("int")
                        .HasColumnName("SELLED");

                    b.Property<bool>("status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<int?>("tagID")
                        .HasColumnType("int")
                        .HasColumnName("TAG_ID");

                    b.Property<DateTime?>("updateAT")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_AT");

                    b.Property<int>("views")
                        .HasColumnType("int")
                        .HasColumnName("VIEWS");

                    b.HasKey("id");

                    b.ToTable("PRODUCTS");
                });
#pragma warning restore 612, 618
        }
    }
}
