// <auto-generated />
using System;
using BaiTap_23WebC_Nhom10.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTap_23WebC_Nhom10.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024153402_InvoiceDetail")]
    partial class InvoiceDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiTap_23WebC_Nhom10.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CATEGORY_NAME");

                    b.Property<bool>("status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("id");

                    b.ToTable("CATEGORY");
                });

            modelBuilder.Entity("BaiTap_23WebC_Nhom10.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryID")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<DateTime>("createAT")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_AT");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DISCOUNT");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IMAGE");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRODUCT_NAME");

                    b.Property<int?>("quanlity")
                        .HasColumnType("int")
                        .HasColumnName("QUANLITY");

                    b.Property<int>("selled")
                        .HasColumnType("int")
                        .HasColumnName("SELLED");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SLUG");

                    b.Property<bool>("status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<int?>("tagID")
                        .HasColumnType("int")
                        .HasColumnName("TAG_ID");

                    b.Property<DateTime?>("updateAT")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_AT");

                    b.Property<int>("views")
                        .HasColumnType("int")
                        .HasColumnName("VIEWS");

                    b.HasKey("id");

                    b.HasIndex("categoryID");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.HasIndex("tagID");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("BaiTap_23WebC_Nhom10.Models.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("tagName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TAG_NAME");

                    b.HasKey("id");

                    b.ToTable("TAGS");
                });

            modelBuilder.Entity("BaiTap_23WebC_Nhom10.Models.Product", b =>
                {
                    b.HasOne("BaiTap_23WebC_Nhom10.Models.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTap_23WebC_Nhom10.Models.Tag", "tag")
                        .WithMany()
                        .HasForeignKey("tagID");

                    b.Navigation("category");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("BaiTap_23WebC_Nhom10.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
